### ISSUE TITLE
mylocation sesnsor questions 

### ISSUE THREAD

**Issue by johntdyer** [ArveVM/MyAssistedHome#115]
I noticed several sensors prefaced w/ "mylocation".... is that from an integration or just your naming convention ?

**Comment by johntdyer** [comment]
hey there, just wanted to check in again and see if you could tell me which integration this sensor uses?

**Comment by ArveVM** [comment]
Hi John
Sorry for not replying sooner,, a bit busy at new job this year - so no time for fun HA-stuff ;)

The mylocation is a naming convention,, did not want to share home location name in config (since it is shared) and wanted something different from "home",,

The sensors are provided by the met-integration for me, but there are several other weather providers -so choose one with good data for your area/country
